version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGPORT: "2710"
    ports:
      - "2710:2710"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge